FROM python:3.6.6
MAINTAINER Raman Prasad (raman_prasad@harvard.edu)

# -------------------------------------
# Install iptables + openssh
# -------------------------------------
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-utils\
    mongodb \
    iptables \
    openssh-client \
    vim

# -------------------------------------
# Set the workdir
# -------------------------------------
WORKDIR /var/apps/mongo_test

# -------------------------------------
# Copy over the requirements and run them
# -------------------------------------
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY mongo_test.py mongo_test.py

# -------------------------------------
# Set environment variables
# -------------------------------------
ENV MONGO_PW=getfromenv

CMD python mongo_test.py
